image: node:13.0.1-alpine

stages:
    - check
    - compile

cache:
    key: 'default'
    paths:
        - node_modules/

before_script:
    - npm install --verbose

check:
    stage: check
    script:
        - npm run lint # includes prettier

compile:
    stage: compile
    script:
        - npm run tsc
