image: node:13.0.1-alpine

stages:
    - install
    - check
    - compile
    - test
    - analysis

cache: &global_cache
    key: '$CI_COMMIT_REF_NAME'
    paths:
        - node_modules/
        - dist/
    policy: pull-push

install:
    stage: install
    script:
        - npm ci --verbose
    cache:
        <<: *global_cache
        policy: push

check:
    stage: check
    script:
        - npm run lint
    cache:
        <<: *global_cache
        policy: pull

compile:
    stage: compile
    script:
        - npm run tsc -- --version
        - npm run tsc
    dependencies:
        - install

test:
    stage: test
    script:
        - export test=True
        - npm run test
    cache:
        <<: *global_cache
        policy: pull

.sonarqube-base:
    stage: analysis
    image: emundo/docker-compose-openjdk-node-sonarqube-scanner:latest
    retry:
        max: 2
        when: runner_system_failure
    allow_failure: true
    dependencies:
        - compile

sonar-job-master:
    extends:
        - .sonarqube-base
    script:
        - npm run sonar-scanner
    only:
        - master

sonar-preview:
    extends:
        - .sonarqube-base
    script:
        - node_modules/sonarqube-scanner/dist/bin/sonar-scanner -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
    only:
        - merge_requests
